const colors = {
  white: "#fff",
  primaryPurple: "#BAA9EC",
  secondaryPurple: "#E8D4FD",
  darkPurple: "#868cff",
  darkPurple2: "#8e93ef",
  purpleLight: "#b9a7ef",
  purpleLight4: "#b9a7ef",
  purpleLight5: "#d5bdfa",
  purpleHoverBg: "#cbbcf59c",
  purpleHoverBg2: "#D9C6F5",
  primaryBlue: "#7EA4F1",
  secondaryBlue: "#84C4FC",
  blueLight: "#749ae7",
  blueLight4: "#bbe2ff",
  blueLight5: "#8e93ef",
  blueLight6: "#9fd6ff",
  blueLightest: "#93cafa",
  chipBg: "#d8cdf69c",
  chipHoverBg: "#cbbcf59c",
  hoverBorder: "#7C81DD",
  lightGrey: "#ccc",
  grey: "#d9d4fe80",
  grey2: "#FFFFFF4D",
  grey3: "#FFFFFF80",
  grey4: "#FFFFFFB3",
  dropDownBg: "#f3f0fd",
  lightPurple: "#7E6BC9",
  dropDownPurpleBorder1: "#BAA9EC",
  dropDownPurpleBorder2: "#7EA4F1",
  dropDownPurpleBorder3: "#84C4FC",
  dropDownSvgPurple: "#7E6BC9",
  dropDownMenuBg: "#f7f4ff",
  paginationBorder: "#C9B7F4",
  disabledGrey: "#F3F3F3",
  lightestGrey: "#B0AFC0",
  boxShadow: "#7A64C966",
  skeletonBg: "#FFFFFF4D"
};

export default colors;
